sensors:
  - wrist_cam
  - fixed_cam

wrist_cam:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /camera/wrist_cam/depth/color/points
  max_range: 5.0
  point_subsample: 1
  padding_offset: 0.1
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: /wrist_cam/filtered_cloud
  self_mask:
    min_sensor_dist: 0.05
    link_names:
      - base_link
      - base
      - link_1
      - link_2
      - link_3
      - link_4
      - link_5
      - link_6
      - cylinder
      - piston
      - flange
      - tool0
      - tcp
      - spindle
      - wrist_cam_mount
      - fixed_cam_mount
      - joint_2_slider

fixed_cam:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /camera/fixed_cam/depth/color/points
  max_range: 5.0
  point_subsample: 1
  padding_offset: 0.1
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: /fixed_cam/filtered_cloud
